# Generated by Django 6.0 on 2026-01-03 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TakeoffJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_pdf', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('openai_key', models.CharField(blank=True, max_length=255, null=True)),
                ('gemini_key', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('highlighted_pdf', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('total_members', models.IntegerField(blank=True, null=True)),
                ('total_types', models.IntegerField(blank=True, null=True)),
                ('total_weight_lbs', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
